AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/TranscribeEmailDemo.zip
      Handler: transcribe.Handler
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 500
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonSESFullAccess
        - AmazonDynamoDBFullAccess
        - AmazonTranscribeFullAccess
        - AmazonWorkMailFullAccess
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: s3-java-lib
      Description: Dependencies for the Java S3 sample app.
      ContentUri: build/s3-java-lib.zip
      CompatibleRuntimes:
        - java8
